title: Shuaijun Wang
email: wukongwoong@gmail.com
description: "Senior Algorithm Engineer at Xiaomi Robotics. Research in dexterous manipulation, tactile sensing, and embodied AI."
github_username: wukongwong
minimal_mistakes_skin: default
search: false

remote_theme: mmistakes/minimal-mistakes

# Custom CSS
custom_css:
  - assets/css/custom.css

markdown: kramdown
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

author:
  name   : "Shuaijun Wang"
  avatar : "assets/images/bio-photo.jpg"
  bio    : "Senior Algorithm Engineer at Xiaomi Robotics. Ph.D. in Robotic Learning. Focusing on dexterous manipulation and embodied AI."
  location: "Beijing, China"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:wukongwoong@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/shuaijun-wang-a3611710b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wukongwong"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=zFDjJeYLL6wC"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:wukongwoong@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/shuaijun-wang-a3611710b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wukongwong"
